site_name: My Docs

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Accueil: index.md
  - Analyse immeuble: immeuble.md
  - analyse du code : code.md